#compiler setup

BEAGLEBONE_EXECUTABLE = gaming-pc

BEAGLEBONE_ENTRY_FILE = server-host.c
BEAGLEBONE_H_LIBRARIES = multicast.h
OUTPUTDIR = $(HOME)/Git/gaming-host
CROSS_TOOL = arm-linux-gnueabihf-
COMPILE_TOOL = gcc
CC_C = $(CROSS_TOOL)$(COMPILE_TOOL)
CFLAGS = -Wall -g -std=c99 -D _POSIX_C_SOURCE=200809L -Werror


all :
	cp ../gaming-libraries/$(BEAGLEBONE_H_LIBRARIES) .
	$(COMPILE_TOOL) $(CFLAGS) $(BEAGLEBONE_ENTRY_FILE) -o $(OUTPUTDIR)/$(BEAGLEBONE_EXECUTABLE)
	rm $(BEAGLEBONE_H_LIBRARIES)



clean :
	rm -f $(OUTPUTDIR)/$(BEAGLEBONE_EXECUTABLE)
